add database
Luis-S-S/quick-call pull request #32
Opened 2022-03-18 19:39 UTC by JesusOsorioJ

### Descripción
Hola profe aca le mando la actualizacion de conexion a db.json

### Feeling
[//]: <> (Como te sientes con este PR? la solucion que entregas como te hace sentir?)
- [ ] 🤙 Solucion rapida
- [x] 👌 Terminado y listo
- [ ] 🤞 Espero que esto funcione, por favor revisar cuidadosamente

### Tickets
[//]: <> (El numero del ticket asociado a este PR)

### Cómo probar?
[//]: <> (Pasos necesarios para probar esta funcionalidad)

### Screenshots (si es aplicable)
[//]: <> (Capturas de pantalla que ayuden a entender que hiciste en este PR)

### Scope

- [ ] 🐞 Bugfix (non-breaking changes que resuelve un problema
- [ ] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
- [x] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
- [ ] ⚠️ Breaking change (cambio que no es compatible con versiones anteriores y/o cambia la funcionalidad actual)

2022-03-18 20:19 UTC, buty619 requested changes
en general los veo muy bien ¡¡ excelente lo unico es que no es una buena practica que desactiven las reglas eslint para el codigo, es mejor buscarle una solución para el error.

2022-03-18 20:19 UTC, buty619 commented on src/Components/Menulateral/VistaMenu/Chats/Chats.jsx
> +/* eslint-disable react/jsx-no-bind */
muchachos en general no es una buena practica que desactiven las reglas eslint para el codigo, es mejor buscarle una solución para el error.

2022-03-18 20:19 UTC, buty619 commented on src/Components/Menulateral/VistaMenu/Contratos/Contratos.jsx
> +/* eslint-disable react/jsx-no-bind */
muchachos en general no es una buena practica que desactiven las reglas eslint para el codigo, es mejor buscarle una solución para el error.

2022-03-18 20:19 UTC, buty619 commented on src/Components/Menulateral/VistaMenu/Contratos/Contratos.jsx
> +        {state.Historico ? (<Historico />) : <span />}
creo que para este caso es mejor hacer un conditional rendering en lugar de colocar un span que no tiene proposito.

`{state.Historico && <Historico />}`

2022-03-18 20:19 UTC, buty619 commented on src/Components/Menulateral/VistaMenu/PQR/PQR.jsx
> +/* eslint-disable react/jsx-no-bind */
muchachos en general no es una buena practica que desactiven las reglas eslint para el codigo, es mejor buscarle una solución para el error.

2022-03-18 20:19 UTC, buty619 commented on src/Pages/Login/Signup.jsx
> +    // const datatosend = {
porfa eliminen el codigo commentado para que no llegue a producción

2022-03-21 19:16 UTC, JesusOsorioJ commented
Hola muchachos aqui subo varios cambios y las correciones del profe, me avisan cualquier cosa

2022-03-22 02:43 UTC, Luis-S-S reviewed
Hola Jesus.
En mi opinión la implementación de redux está bien. No entiendo muy bien el cambio de carpetas que hiciste con home.jsx y login.jsx creo que las sacaste de la carpeta pero no sé por qué. También las bases de datos en la carpeta data están en español en lugar de inglés que siento debemos tener uniforme en todas las bases de datos.

2022-03-22 15:38 UTC, franciscocruz29 approved these changes

2022-03-22 16:01 UTC, merged